[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = "1.0.0"
reqwest = "0.11.0"
async-trait = "0.1.0"
rand = "0.8.4"
regex = "1.5.4"
